
Browser = Chrome
URL = https://auto.mahindra.com/
#URL = https://storefront:amc2024@sfcc-staging-auto.mahindra.com/
mobileNumber = 9987009796
eKycData = AAECB2434L

excelDataPath = C:\\Users\\Rahul Chauhan\\eclipse-workspace\\AMCTest\\src\\main\\java\\com\\amc\\qa\\data\\ContactUs.xlsx
sheetName = Sheet1
